# Generated by Django 4.1 on 2022-09-28 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Breakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(verbose_name='Reportado el')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('description_fails', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('start_repair', models.DateField(verbose_name='Inicio de Reparacion el')),
                ('end_repair', models.DateField(null=True, verbose_name='Fin de Reparacion el')),
                ('status', models.CharField(choices=[('Atendida', 'Atendida'), ('No atendida', 'No atendida')], default='Atendida', max_length=20, verbose_name='Estatus')),
            ],
            options={
                'verbose_name': 'Averia',
                'verbose_name_plural': 'Averias',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=60, verbose_name='Apellidos')),
                ('document_type', models.CharField(choices=[('Cedula', 'Cedula'), ('Pasaporte', 'Pasaporte')], default='Cedula', max_length=20, verbose_name='Tipo de documento')),
                ('document_number', models.IntegerField(verbose_name='Numero De Documento')),
                ('company', models.CharField(blank=True, max_length=80, null=True, verbose_name='empresa')),
                ('phone', models.CharField(max_length=20, verbose_name='Numero de telefono')),
                ('car', models.CharField(blank=True, max_length=30, null=True, verbose_name='vehiculo')),
                ('license_plate', models.CharField(blank=True, max_length=10, null=True, verbose_name='Placa Vehiculo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('mail', models.EmailField(max_length=250, verbose_name='Correo')),
                ('address', models.CharField(max_length=250, verbose_name='Direccion')),
                ('phone', models.CharField(max_length=20, verbose_name='Numero de Telefono')),
                ('rif', models.CharField(max_length=40, verbose_name='Rif')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=60, verbose_name='Nombre')),
                ('identification_card', models.IntegerField(verbose_name='Numero de Cedula')),
                ('occupation', models.CharField(max_length=60, verbose_name='Ocupacion')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_entry', models.CharField(max_length=50, verbose_name='Tipo de Ingreso')),
                ('type_reservation', models.CharField(default='No Cancelada', max_length=50, verbose_name='Tipo de Reservacion')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observacion')),
                ('payment_type', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Trasnferencia', 'Trasnferencia'), ('Debito', 'Debito'), ('Zelle', 'Zelle'), ('Binance', 'Binance')], default='Efectivo', max_length=20, verbose_name='Tipo de Pago')),
                ('payment_details', models.CharField(max_length=250, verbose_name='Detalles del Pago')),
                ('total', models.FloatField(null=True, verbose_name='Total')),
                ('customer_debt', models.FloatField(blank=True, null=True, verbose_name='Deuda Cliente')),
                ('hotel_debt', models.FloatField(blank=True, null=True, verbose_name='Deuda Hotel')),
                ('received', models.FloatField(verbose_name='Dinero Recibido')),
                ('entry_at', models.DateField(verbose_name='Entrada el')),
                ('exit_at', models.DateField(blank=True, null=True, verbose_name='Salida el')),
                ('guest_exit', models.CharField(default='No', max_length=2, null=True, verbose_name='salida')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='app.client')),
            ],
            options={
                'verbose_name': 'Huesped',
                'verbose_name_plural': 'Huespedes',
            },
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Extra')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('amount', models.FloatField(verbose_name='Monto Extra')),
            ],
            options={
                'verbose_name': 'Extra',
                'verbose_name_plural': 'Extras',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=3, verbose_name='Numero de Habitacion')),
                ('room_type', models.CharField(choices=[('Estandar', 'Estandar'), ('Estandar Ejecutiva', 'Estandar Ejecutiva'), ('Matrimonial Doble', 'Matrimonial Doble'), ('Triple (2 Queen y Sofa Cama)', 'Triple (2 Queen y Sofa Cama)'), ('Master King', 'Master King')], default='Estandar', max_length=40, verbose_name='Tipo de Habitacion')),
                ('observation', models.TextField(verbose_name='Observaciones')),
                ('room_price', models.FloatField(verbose_name='Precio de Habitacion')),
            ],
            options={
                'verbose_name': 'Habitacion',
                'verbose_name_plural': 'Habitaciones',
            },
        ),
        migrations.CreateModel(
            name='Ropen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.breakdown', verbose_name='Falla')),
                ('receptionist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Recepcionista Abre Reporte')),
            ],
            options={
                'verbose_name': 'Reporte Abierto',
                'verbose_name_plural': 'Reportes Abiertos',
            },
        ),
        migrations.CreateModel(
            name='Room_Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('Habilitada', 'Habilitada'), ('Disponible', 'Disponible'), ('Ocupada', 'Ocupada'), ('Reservada', 'Reservada'), ('En espera', 'En espera'), ('Averiada', 'Averiada')], default='Habilitada', max_length=20, verbose_name='Estado de la Habitacion')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.room')),
            ],
            options={
                'verbose_name': 'Habitacion Condicion',
            },
        ),
        migrations.CreateModel(
            name='Remployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee', verbose_name='Empleado')),
                ('failure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.breakdown', verbose_name='Falla')),
            ],
            options={
                'verbose_name': 'Reporte Empleado',
                'verbose_name_plural': 'Reportes Empleados',
            },
        ),
        migrations.CreateModel(
            name='Rclose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.breakdown', verbose_name='Falla')),
                ('receptionist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Recepcionista Cierre Falla')),
            ],
            options={
                'verbose_name': 'Reporte Cerrado',
                'verbose_name_plural': 'Reportes Cerrados',
            },
        ),
        migrations.CreateModel(
            name='Memployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee', verbose_name='Empleado Mtto')),
                ('failure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.breakdown', verbose_name='Falla')),
            ],
            options={
                'verbose_name': 'Personal Mantenimiento',
                'verbose_name_plural': 'Personal Mantenimientos',
            },
        ),
        migrations.CreateModel(
            name='Entry_extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.entry')),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.extra')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='extra',
            field=models.ManyToManyField(through='app.Entry_extra', to='app.extra'),
        ),
        migrations.AddField(
            model_name='entry',
            name='receptionist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entry',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.room'),
        ),
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_in', models.FloatField(verbose_name='Saldo Entrada')),
                ('balance_out', models.FloatField(verbose_name='Saldo Salida')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('receptionist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caja Chica',
            },
        ),
        migrations.AddField(
            model_name='breakdown',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.entry'),
        ),
        migrations.AddField(
            model_name='breakdown',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.room'),
        ),
    ]
