# Generated by Django 4.1 on 2022-09-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='condition',
            field=models.CharField(choices=[('Habilitada', 'Habilitada'), ('Disponible', 'Disponible'), ('Ocupada', 'Ocupada'), ('Reservada', 'Reservada'), ('En espera', 'En espera'), ('Averiada', 'Averiada')], default='Habilitada', max_length=20, verbose_name='Estado de la Habitacion'),
        ),
        migrations.AlterField(
            model_name='room_condition',
            name='condition',
            field=models.CharField(choices=[('Habilitada', 'Habilitada'), ('Disponible', 'Disponible'), ('Ocupada', 'Ocupada'), ('Reservada', 'Reservada'), ('En espera', 'En espera'), ('Averiada', 'Averiada')], default='Habilitada', max_length=20, null=True, verbose_name='Estado de la Habitacion'),
        ),
    ]
